"""Add student_id to Participant and enforce uniqueness

Revision ID: 986b8088eb9e
Revises: 5e5d9e2001ef
Create Date: 2024-12-01 16:55:22.399081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986b8088eb9e'
down_revision = '5e5d9e2001ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.String(length=15), nullable=False))
        batch_op.drop_index('unique_event_name')
        batch_op.create_unique_constraint('unique_event_student_id', ['event_id', 'student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_constraint('unique_event_student_id', type_='unique')
        batch_op.create_index('unique_event_name', ['event_id', 'name'], unique=True)
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
